#!/bin/bash

writeprototypes() {
  echo "Writting function Indexing_$1() ..."
  sed -i -e "$2 i PetscErrorCode Indexing_$1 ($1_MODEL *item, PetscInt index, PetscInt *start);" Indexing_StateVar.h

}

linenumber=37
while IFS= read -r file2
	do
  writeprototypes $file2 $linenumber
  linenumber=$((linenumber+1))
done < "models"
